### ISSUE TITLE
Iterating without closing

### ISSUE THREAD

**Issue by subashy21** [matthuisman/service.iptv.merge#1]
Hi !
In the first place good job for this addon, I use it for the moment in a devious way for update my m3u playlist everyday.
I adapted your code a bit to modify my playlist while waiting for something better.

I'm a novice in python development but i notice something weird in your code.
You initialize file openings without closing them. I understand that this isn't a good practice, the files stay open and it's better to close them for free up system resources.
This part in service.py:
```
def process_file(item):
if item.path_type == Source.TYPE_REMOTE:
    r = Session().get(item.path, stream=True)
    r.raise_for_status()
    in_file = StringIO.StringIO(r.content)

elif item.path_type == Source.TYPE_LOCAL:
    in_file = open(xbmc.translatePath(item.path))

if item.file_type == Source.FILE_GZIP:
    in_file = gzip.GzipFile(fileobj=in_file)

    return in_file.read()
```
I may be wrong, in any case you made me want to code with your plugin. ;)

**Comment by matthuisman** [comment]
https://github.com/matthuisman/service.iptv.merge/commit/d3bd6b33f0b1a65e7f730318fcd74c72216c2440
